apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}

spec:
  selector:
    app: {{ include "mlflow.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
  type: {{ .Values.service.type }}